const Product = require('../../domain/models/product');

class ProductRepository {
  constructor() {
    this.products = [
      new Product({
        id: 1,
        title: "Correa reflectante a prueba de explosiones para perros",
        description: "Correa para perros reflectante a prueba de explosiones, correa redonda de cadena para perros, correa universal para todo tipo de perros.",
        rating: 4,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Rojo", "Azul", "Negro"],
        specifications: ["S - 10cm", "M - 15cm", "L - 20cm"],
        inventory: 99617,
        price: 1.4,
        suggestedPrice: 2.5,
        unitCost: 1.4,
        marginPerUnit: 1.1,
        marginPercentage: 44,
        material: "Nylon",
        packingQuantity: 50,
        origin: "China",
        scalable: false,
        category: "Suministros para Mascotas",
        weight: "0.2kg",
        dimensions: "10x2x2 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 2,
        title: "Juguete mordedor duradero para perros",
        description: "Juguete mordedor fuerte y duradero para perros, perfecto para perros con mordida agresiva.",
        rating: 5,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Verde", "Amarillo", "Naranja"],
        specifications: ["S - 5cm", "M - 10cm", "L - 15cm"],
        inventory: 50000,
        price: 3.5,
        suggestedPrice: 5.0,
        unitCost: 3.0,
        marginPerUnit: 2.0,
        marginPercentage: 40,
        material: "Goma",
        packingQuantity: 100,
        origin: "Estados Unidos",
        scalable: true,
        category: "Juguetes para Mascotas",
        weight: "0.3kg",
        dimensions: "5x5x5 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 3,
        title: "Arnés ajustable para perros",
        description: "Arnés ajustable y cómodo para perros con franjas reflectantes para mayor seguridad.",
        rating: 4.5,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Negro", "Gris"],
        specifications: ["S - 25cm", "M - 35cm", "L - 45cm"],
        inventory: 20000,
        price: 10.0,
        suggestedPrice: 15.0,
        unitCost: 8.0,
        marginPerUnit: 5.0,
        marginPercentage: 33,
        material: "Poliéster",
        packingQuantity: 20,
        origin: "China",
        scalable: false,
        category: "Suministros para Mascotas",
        weight: "0.5kg",
        dimensions: "20x15x5 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 4,
        title: "Rascador para gatos",
        description: "Rascador para gatos con recubrimiento de sisal resistente.",
        rating: 4,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Beige", "Marrón"],
        specifications: ["Altura - 50cm", "Base - 30x30cm"],
        inventory: 10000,
        price: 20.0,
        suggestedPrice: 25.0,
        unitCost: 15.0,
        marginPerUnit: 5.0,
        marginPercentage: 20,
        material: "Sisal, Madera",
        packingQuantity: 10,
        origin: "Vietnam",
        scalable: true,
        category: "Mobiliario para Mascotas",
        weight: "2.0kg",
        dimensions: "50x30x30 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 5,
        title: "Comedero automático para mascotas",
        description: "Comedero automático programable para perros y gatos.",
        rating: 4.7,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Blanco", "Negro"],
        specifications: ["Capacidad - 5L", "Funciona con baterías"],
        inventory: 8000,
        price: 50.0,
        suggestedPrice: 65.0,
        unitCost: 40.0,
        marginPerUnit: 15.0,
        marginPercentage: 30,
        material: "Plástico",
        packingQuantity: 5,
        origin: "China",
        scalable: true,
        category: "Suministros para Mascotas",
        weight: "1.5kg",
        dimensions: "30x20x20 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 6,
        title: "Bolsa de transporte para mascotas",
        description: "Bolsa de transporte ligera para mascotas pequeñas, como perros y gatos.",
        rating: 4.2,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Gris", "Azul"],
        specifications: ["Pequeño - 30cm", "Mediano - 45cm", "Grande - 60cm"],
        inventory: 15000,
        price: 25.0,
        suggestedPrice: 35.0,
        unitCost: 20.0,
        marginPerUnit: 10.0,
        marginPercentage: 28,
        material: "Tela",
        packingQuantity: 15,
        origin: "Italia",
        scalable: false,
        category: "Viaje para Mascotas",
        weight: "0.8kg",
        dimensions: "60x40x40 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 7,
        title: "Fuente de agua para mascotas",
        description: "Fuente de agua automática con filtro para proporcionar agua fresca continuamente.",
        rating: 4.8,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Blanco", "Verde"],
        specifications: ["Capacidad - 2L", "Funciona con USB"],
        inventory: 5000,
        price: 35.0,
        suggestedPrice: 45.0,
        unitCost: 30.0,
        marginPerUnit: 15.0,
        marginPercentage: 30,
        material: "Plástico",
        packingQuantity: 10,
        origin: "Corea",
        scalable: true,
        category: "Suministros para Mascotas",
        weight: "1.0kg",
        dimensions: "25x20x15 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 8,
        title: "Cepillo para mascotas",
        description: "Cepillo suave para el cuidado de mascotas, adecuado para todo tipo de animales.",
        rating: 4.3,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Rosa", "Verde"],
        specifications: ["Tamaño único"],
        inventory: 25000,
        price: 7.0,
        suggestedPrice: 9.5,
        unitCost: 5.0,
        marginPerUnit: 2.0,
        marginPercentage: 28,
        material: "Plástico, Goma",
        packingQuantity: 100,
        origin: "Alemania",
        scalable: false,
        category: "Cuidado de Mascotas",
        weight: "0.1kg",
        dimensions: "10x5x2 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 9,
        title: "Cortaúñas para mascotas",
        description: "Cortaúñas de acero inoxidable para mascotas, ideal para cortar uñas fácilmente.",
        rating: 4.5,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Rojo", "Azul"],
        specifications: ["Tamaño único"],
        inventory: 10000,
        price: 12.0,
        suggestedPrice: 18.0,
        unitCost: 10.0,
        marginPerUnit: 6.0,
        marginPercentage: 33,
        material: "Acero inoxidable",
        packingQuantity: 50,
        origin: "Japón",
        scalable: true,
        category: "Cuidado de Mascotas",
        weight: "0.2kg",
        dimensions: "8x4x1 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 10,
        title: "Colchón para perros y gatos",
        description: "Colchón cómodo y resistente para mascotas, fácil de limpiar.",
        rating: 4.6,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Gris", "Negro"],
        specifications: ["Pequeño - 60cm", "Grande - 100cm"],
        inventory: 12000,
        price: 30.0,
        suggestedPrice: 40.0,
        unitCost: 25.0,
        marginPerUnit: 15.0,
        marginPercentage: 38,
        material: "Espuma, Tela",
        packingQuantity: 20,
        origin: "Brasil",
        scalable: true,
        category: "Mobiliario para Mascotas",
        weight: "1.0kg",
        dimensions: "60x40x10 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 11,
        title: "Juguete interactivo para gatos",
        description: "Juguete interactivo con luces para mantener a los gatos entretenidos.",
        rating: 4.9,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Blanco", "Azul"],
        specifications: ["Un tamaño"],
        inventory: 5000,
        price: 15.0,
        suggestedPrice: 20.0,
        unitCost: 10.0,
        marginPerUnit: 5.0,
        marginPercentage: 25,
        material: "Plástico",
        packingQuantity: 25,
        origin: "México",
        scalable: true,
        category: "Juguetes para Mascotas",
        weight: "0.5kg",
        dimensions: "10x5x5 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
      new Product({
        id: 12,
        title: "Cama elevada para mascotas",
        description: "Cama elevada para mascotas, ideal para mantener a las mascotas frescas y cómodas.",
        rating: 4.8,
        image: "https://via.placeholder.com/100",
        quantity: 1,
        colors: ["Verde", "Negro"],
        specifications: ["Mediano - 90cm", "Grande - 120cm"],
        inventory: 7500,
        price: 45.0,
        suggestedPrice: 60.0,
        unitCost: 35.0,
        marginPerUnit: 15.0,
        marginPercentage: 30,
        material: "Metal, Tela",
        packingQuantity: 10,
        origin: "España",
        scalable: true,
        category: "Mobiliario para Mascotas",
        weight: "2.5kg",
        dimensions: "90x60x15 cm",
        thumbnails: [
          "https://via.placeholder.com/100x100?text=Thumb1",
          "https://via.placeholder.com/100x100?text=Thumb2",
          "https://via.placeholder.com/100x100?text=Thumb3",
          "https://via.placeholder.com/100x100?text=Thumb4",
        ],
      }),
    ];
  }

  getAllProducts() {
    return this.products;
  }

  getProductById(id) {
    return this.products.find((product) => product.id === parseInt(id));
  }
}

module.exports = ProductRepository;
